init:
  app: bqwt
  target:
    URL: ssh://127.0.0.1/
    credentials: localhost
  appHost: $Hostname($target.URL)
  bqCredentials: viant-e2e
defaults:
  app: $app
  target: $target
  buildTarget: $buildTarget
  appTarget: $appTarget
  bqCredentials: $bqCredentials
pipeline:
  init:
    datastore:
      action: run
      request: '@datastore'
      tasks: '*'
    app:
      sdk: $sdk
      action: run
      request: '@app'
      tasks: '*'
  test:
    action: run
    request: '@regression/regression'
    tasks: '*'
  destroy:
    app:
      buildTarget: $target
      app: $app
      appVersion: $appVersion
      action: run
      request: '@app'
      tasks: stop
